network_topology:
  ros__parameters:
    # 0 = multi to one, 1 = one to one
    architecture: 1
    num_of_atr_groups: 1
    num_of_atr_in_groups: 245
    delay: 0.5
    start_id: 0

atr_bot:
  ros__parameters:
    state_publisher_period: 100
    num_of_connected_atr: 245
    package: atr_bot
    executable: atr_bot
    node_base_name: atr_bot_
    state_topic_name: state_
    base_position: 
      x: 0
      y: 0
      z: 0

atr_tracker:
  ros__parameters:
    package: atr_tracker
    executable: atr_tracker
    node_base_name: atr_tracker
    debug: false
    list_publisher_period: 100
    #num_of_connected_atr: 50   

atr_state_list_subscriber:
  ros__parameters:
    # Reference frame for the visualization objects
    frame_id: map
    # Namespace to group the visualization markers
    marker_namespace: atr_states_objects
    # Topic name for the marker array
    marker_topic_name: atr_markers
    # Topic name where the ATRState will be published. This node transforms this state into visualization markers
    subs_topic_name: atr_state_list
